spring:
  data:    mongodb:
      uri: mongodb+srv://adminuser:adminpass@cluster0.rm6uo0x.mongodb.net/?retryWrites=true&w=majority
      
server:
  port: 8888
  
#spring.data.mongodb.uri = mongodb+srv://adminuser:adminpass@cluster0.rm6uo0x.mongodb.net/?retryWrites=true&w=majority
#server.port = 8888